const C={"content-type":"application/json;charset=utf-8","access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS","access-control-allow-headers":"Content-Type,Authorization","cache-control":"no-store"};
const J=(x,s=200,extra={})=>new Response(JSON.stringify(x),{status:s,headers:{...C,...extra}});
const clean=(x,n=5000)=>String(x??'').trim().slice(0,n);
const tokenFrom=r=>(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();
let schemaReady=null;
async function sha256(s){const b=new TextEncoder().encode(s);const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function now(){return Date.now()}
function iso(ms){return new Date(ms).toISOString()}
function daysLeft(expiresAt){return Math.ceil((Number(expiresAt)-now())/86400000)}
function makeSlug(id){return 't-'+String(id).toLowerCase().replace(/[^a-z0-9_-]/g,'-')+'-'+crypto.randomUUID().slice(0,8)}
async function ensureSchema(e){
  if(schemaReady)return schemaReady;
  schemaReady=(async()=>{
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_auth (id INTEGER PRIMARY KEY CHECK(id=1), password_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT(datetime('now')), updated_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_sessions (token TEXT PRIMARY KEY, expires_at INTEGER NOT NULL)`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS comments (id TEXT PRIMARY KEY, name TEXT NOT NULL, text TEXT NOT NULL, image TEXT DEFAULT '', created_at TEXT NOT NULL DEFAULT(datetime('now')), visible INTEGER NOT NULL DEFAULT 1)`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS view_daily (day TEXT NOT NULL, kind TEXT NOT NULL, product_id TEXT NOT NULL DEFAULT '', views INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(day,kind,product_id))`).run();
    await e.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_view_daily_day ON view_daily(day)`).run();
    try{await e.DB.prepare(`ALTER TABLE tags ADD COLUMN parent_id TEXT DEFAULT NULL`).run()}catch{}
    try{await e.DB.prepare(`ALTER TABLE settings ADD COLUMN value TEXT`).run()}catch{}
    const row=await e.DB.prepare('SELECT id FROM admin_auth WHERE id=1').first();
    if(!row)await e.DB.prepare('INSERT INTO admin_auth(id,password_hash) VALUES(1,?)').bind(await sha256('123456')).run();
    await e.DB.prepare(`INSERT OR IGNORE INTO settings(key,value) VALUES('adminZalo','"#"')`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_accounts(
      tenant_id TEXT PRIMARY KEY, password_hash TEXT NOT NULL, slug TEXT NOT NULL UNIQUE,
      starts_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, delete_after INTEGER,
      locked INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT(datetime('now')), updated_at TEXT NOT NULL DEFAULT(datetime('now'))
    )`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_sessions(token TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
    await e.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_tenant_sessions_tenant ON tenant_sessions(tenant_id)`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_products(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,title TEXT NOT NULL,game TEXT NOT NULL DEFAULT '',description TEXT DEFAULT '',thumb TEXT DEFAULT '',download_link TEXT NOT NULL,warning TEXT DEFAULT '',views INTEGER NOT NULL DEFAULT 0,visible INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
    await e.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_tenant_products_tenant ON tenant_products(tenant_id)`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_tags(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name TEXT NOT NULL,parent_id TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
    await e.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_tenant_tags_tenant ON tenant_tags(tenant_id)`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_comments(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name TEXT NOT NULL,text TEXT NOT NULL,image TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT(datetime('now')),visible INTEGER NOT NULL DEFAULT 1)`).run();
    await e.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_tenant_comments_tenant ON tenant_comments(tenant_id)`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_settings(tenant_id TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(tenant_id,key))`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_views(day TEXT NOT NULL,tenant_id TEXT NOT NULL,kind TEXT NOT NULL,product_id TEXT NOT NULL DEFAULT '',views INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(day,tenant_id,kind,product_id))`).run();
    await e.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_tenant_views_tenant_day ON tenant_views(tenant_id,day)`).run();
    await e.DB.prepare(`CREATE TABLE IF NOT EXISTS tenant_audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_id TEXT NOT NULL,action TEXT NOT NULL,detail TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT(datetime('now')))`).run();
  })();
  return schemaReady;
}
async function isAdmin(r,e){const t=tokenFrom(r);if(!t)return false;await ensureSchema(e);const x=await e.DB.prepare('SELECT token FROM admin_sessions WHERE token=? AND expires_at>?').bind(t,now()).first();return !!x}
async function tenantFromSession(r,e){const t=tokenFrom(r);if(!t)return null;await ensureSchema(e);const x=await e.DB.prepare(`SELECT a.*,s.expires_at AS session_expires_at FROM tenant_sessions s JOIN tenant_accounts a ON a.tenant_id=s.tenant_id WHERE s.token=? AND s.expires_at>?`).bind(t,now()).first();if(!x||Number(x.locked))return null;if(Number(x.expires_at)<=now())return null;return x}
async function tenantBySlug(e,slug){return await e.DB.prepare('SELECT * FROM tenant_accounts WHERE slug=?').bind(clean(slug,160)).first()}
async function purgeExpired(e){const cutoff=now()-6*86400000;const rows=(await e.DB.prepare(`SELECT tenant_id FROM tenant_accounts WHERE expires_at<=? AND COALESCE(delete_after,expires_at+518400000)<=?`).bind(now(),now()).all()).results||[];for(const x of rows){const id=x.tenant_id;await e.DB.batch([
  e.DB.prepare('DELETE FROM tenant_sessions WHERE tenant_id=?').bind(id),e.DB.prepare('DELETE FROM tenant_products WHERE tenant_id=?').bind(id),e.DB.prepare('DELETE FROM tenant_tags WHERE tenant_id=?').bind(id),e.DB.prepare('DELETE FROM tenant_comments WHERE tenant_id=?').bind(id),e.DB.prepare('DELETE FROM tenant_settings WHERE tenant_id=?').bind(id),e.DB.prepare('DELETE FROM tenant_views WHERE tenant_id=?').bind(id),e.DB.prepare('DELETE FROM tenant_audit_log WHERE tenant_id=?').bind(id),e.DB.prepare('DELETE FROM tenant_accounts WHERE tenant_id=?').bind(id)
]);}}
async function tenantInfo(a){return {id:a.tenant_id,slug:a.slug,startsAt:a.starts_at,expiresAt:a.expires_at,deleteAfter:a.delete_after,locked:!!Number(a.locked),daysLeft:daysLeft(a.expires_at),status:Number(a.locked)?'locked':(Number(a.expires_at)<=now()?'expired':daysLeft(a.expires_at)<=7?'expiring':'active')}}
async function tenantSettings(e,id){const a=(await e.DB.prepare('SELECT key,value FROM tenant_settings WHERE tenant_id=?').bind(id).all()).results||[];const s={siteName:'Lại Húp File',studio:'Téo Studio',heroTitle:'Téo Studio',heroText:'Kho code, script, tool và tài nguyên game được cập nhật.',avatar:'assets/img/default-avatar.svg',announcementTitle:'Thông báo',announcementText:'',announcementEnabled:true,groupLink:'#',adminContact:'#',adminZalo:'#',donateTitle:'Donate Téo',donateText:'',donateQr:''};for(const x of a){try{s[x.key]=JSON.parse(x.value)}catch{s[x.key]=x.value}}return s}
async function tenantTags(e,id){return (await e.DB.prepare('SELECT id,name,parent_id,created_at FROM tenant_tags WHERE tenant_id=? ORDER BY CASE WHEN parent_id IS NULL OR parent_id=\'\' THEN 0 ELSE 1 END,name COLLATE NOCASE').bind(id).all()).results||[]}
async function tenantProducts(e,id){return (await e.DB.prepare('SELECT * FROM tenant_products WHERE tenant_id=? AND visible=1 ORDER BY updated_at DESC').bind(id).all()).results||[]}
async function tenantAdminProducts(e,id){return (await e.DB.prepare('SELECT * FROM tenant_products WHERE tenant_id=? ORDER BY updated_at DESC').bind(id).all()).results||[]}
async function tenantProductById(e,id,pid){return await e.DB.prepare('SELECT * FROM tenant_products WHERE tenant_id=? AND id=? AND visible=1').bind(id,pid).first()}
function dayVN(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
async function bumpView(e,kind,productId=''){const day=dayVN();await e.DB.prepare(`INSERT INTO view_daily(day,kind,product_id,views) VALUES(?,?,?,1) ON CONFLICT(day,kind,product_id) DO UPDATE SET views=views+1`).bind(day,kind,productId).run();if(kind==='product'&&productId)await e.DB.prepare('UPDATE products SET views=COALESCE(views,0)+1 WHERE id=?').bind(productId).run()}
async function bumpTenantView(e,tid,kind,pid=''){const day=dayVN();await e.DB.prepare(`INSERT INTO tenant_views(day,tenant_id,kind,product_id,views) VALUES(?,?,?,?,1) ON CONFLICT(day,tenant_id,kind,product_id) DO UPDATE SET views=views+1`).bind(day,tid,kind,pid).run();if(kind==='product'&&pid)await e.DB.prepare('UPDATE tenant_products SET views=COALESCE(views,0)+1 WHERE tenant_id=? AND id=?').bind(tid,pid).run()}
async function comments(e){return (await e.DB.prepare('SELECT id,name,text,image,created_at FROM comments WHERE visible=1 ORDER BY created_at DESC LIMIT 50').all()).results||[]}
async function stats(e,days=30){const n=Math.max(7,Math.min(Number(days)||30,365));const rows=(await e.DB.prepare(`SELECT day,kind,product_id,views FROM view_daily WHERE day>=date(?, '-'||?||' days') ORDER BY day ASC`).bind(dayVN(),n-1).all()).results||[];const prods=await e.DB.prepare('SELECT id,title,views FROM products ORDER BY views DESC,updated_at DESC').all();return {days:n,rows,products:prods.results||[],today:rows.filter(x=>x.day===dayVN()).reduce((a,x)=>a+Number(x.views||0),0)} }
async function tenantStats(e,tid,days=30){const n=Math.max(7,Math.min(Number(days)||30,365));const rows=(await e.DB.prepare(`SELECT day,kind,product_id,views FROM tenant_views WHERE tenant_id=? AND day>=date(?, '-'||?||' days') ORDER BY day ASC`).bind(tid,dayVN(),n-1).all()).results||[];const prods=await e.DB.prepare('SELECT id,title,views FROM tenant_products WHERE tenant_id=? ORDER BY views DESC,updated_at DESC').bind(tid).all();return {days:n,rows,products:prods.results||[],today:rows.filter(x=>x.day===dayVN()).reduce((a,x)=>a+Number(x.views||0),0)} }
async function tenantAudit(e,id,action,detail=''){await e.DB.prepare('INSERT INTO tenant_audit_log(tenant_id,action,detail) VALUES(?,?,?)').bind(id,action,clean(detail,1000)).run()}
async function handleTenantPublic(r,e,p){
  const parts=p.split('/').filter(Boolean);const slug=parts[1];const a=await tenantBySlug(e,slug);if(!a)return J({ok:false,error:'TENANT_NOT_FOUND'},404);if(Number(a.locked))return J({ok:false,error:'TENANT_LOCKED'},403);if(Number(a.expires_at)<=now())return J({ok:false,error:'TENANT_EXPIRED',deleteAfter:a.delete_after||Number(a.expires_at)+518400000},403);
  if(parts.length===2&&r.method==='GET')return J({ok:true,tenant:tenantInfo(a),settings:await tenantSettings(e,a.tenant_id),products:await tenantProducts(e,a.tenant_id),tags:await tenantTags(e,a.tenant_id)});
  if(parts[2]==='product'&&parts[3]&&r.method==='GET'){const x=await tenantProductById(e,a.tenant_id,decodeURIComponent(parts[3]));return x?J({ok:true,product:x,tenant:tenantInfo(a),settings:await tenantSettings(e,a.tenant_id)}):J({ok:false,error:'NOT_FOUND'},404)}
  if(parts[2]==='track'&&parts[3]&&r.method==='POST'){const kind=parts[3];const pid=parts[4]||'';if(['site','product','outbound'].includes(kind)){if(kind==='product'||kind==='outbound'){const x=await tenantProductById(e,a.tenant_id,decodeURIComponent(pid));if(!x)return J({ok:false,error:'NOT_FOUND'},404)}await bumpTenantView(e,a.tenant_id,kind,decodeURIComponent(pid));return J({ok:true})}}
  if(parts[2]==='comments'&&r.method==='GET')return J({ok:true,comments:(await e.DB.prepare('SELECT id,name,text,image,created_at FROM tenant_comments WHERE tenant_id=? AND visible=1 ORDER BY created_at DESC LIMIT 50').bind(a.tenant_id).all()).results||[]});
  if(parts[2]==='comments'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const name=clean(b.name,40)||'Ẩn danh',text=clean(b.text,700),image=clean(b.image,1000000);if(!text&&!image)return J({ok:false,error:'COMMENT_EMPTY'},400);const id=crypto.randomUUID();await e.DB.prepare('INSERT INTO tenant_comments(id,tenant_id,name,text,image) VALUES(?,?,?,?,?)').bind(id,a.tenant_id,name,text,image).run();return J({ok:true,id},201)}
  return J({ok:false,error:'NOT_FOUND'},404)
}
async function handleTenantAdmin(r,e,p){
  const t=await tenantFromSession(r,e);if(!t)return J({ok:false,error:'TENANT_AUTH_REQUIRED'},401);const id=t.tenant_id;const info=tenantInfo(t);
  if(p==='/api/tenant/me'&&r.method==='GET')return J({ok:true,tenant:info,settings:await tenantSettings(e,id)});
  if(p==='/api/tenant/logout'&&r.method==='POST'){const tok=tokenFrom(r);await e.DB.prepare('DELETE FROM tenant_sessions WHERE token=?').bind(tok).run();return J({ok:true})}
  if(p==='/api/tenant/change-password'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const pw=String(b.newPassword||'');if(pw.length<6)return J({ok:false,error:'PASSWORD_TOO_SHORT'},400);await e.DB.prepare('UPDATE tenant_accounts SET password_hash=?,updated_at=datetime(\'now\') WHERE tenant_id=?').bind(await sha256(pw),id).run();await e.DB.prepare('DELETE FROM tenant_sessions WHERE tenant_id=?').bind(id).run();await tenantAudit(e,id,'change_password','Tenant đổi mật khẩu');return J({ok:true,reauth:true})}
  if(p==='/api/tenant/products'&&r.method==='GET')return J({ok:true,products:await tenantAdminProducts(e,id)});
  if(p==='/api/tenant/products'&&r.method==='POST'){const b=await r.json();if(!b.title||!b.download_link)return J({ok:false,error:'title_and_download_link_required'},400);const pid=crypto.randomUUID();await e.DB.prepare('INSERT INTO tenant_products(id,tenant_id,title,game,description,thumb,download_link,warning,visible) VALUES(?,?,?,?,?,?,?,?,1)').bind(pid,id,clean(b.title,200),clean(b.game,100),clean(b.description),clean(b.thumb,1500000),clean(b.download_link,10000),clean(b.warning)).run();await tenantAudit(e,id,'create_product',pid);return J({ok:true,id:pid},201)}
  let pm=p.match(/^\/api\/tenant\/products\/([^/]+)$/);if(pm){const pid=decodeURIComponent(pm[1]);if(r.method==='DELETE'){await e.DB.prepare('DELETE FROM tenant_products WHERE tenant_id=? AND id=?').bind(id,pid).run();await tenantAudit(e,id,'delete_product',pid);return J({ok:true})}if(r.method==='PUT'){const b=await r.json();await e.DB.prepare('UPDATE tenant_products SET title=?,game=?,description=?,thumb=?,download_link=?,warning=?,updated_at=datetime(\'now\') WHERE tenant_id=? AND id=?').bind(clean(b.title,200),clean(b.game,100),clean(b.description),clean(b.thumb,1500000),clean(b.download_link,10000),clean(b.warning),id,pid).run();await tenantAudit(e,id,'update_product',pid);return J({ok:true})}}
  if(p==='/api/tenant/tags'&&r.method==='GET')return J({ok:true,tags:await tenantTags(e,id)});
  if(p==='/api/tenant/tags'&&r.method==='POST'){const b=await r.json(),name=clean(b.name,100),parentId=clean(b.parent_id,100)||null;if(!name)return J({ok:false,error:'name_required'},400);const tid=crypto.randomUUID();await e.DB.prepare('INSERT INTO tenant_tags(id,tenant_id,name,parent_id) VALUES(?,?,?,?)').bind(tid,id,name,parentId).run();return J({ok:true,id:tid},201)}
  let tm=p.match(/^\/api\/tenant\/tags\/([^/]+)$/);if(tm){const tid=decodeURIComponent(tm[1]);if(r.method==='DELETE'){await e.DB.prepare('DELETE FROM tenant_tags WHERE tenant_id=? AND (id=? OR parent_id=?)').bind(id,tid,tid).run();return J({ok:true})}if(r.method==='PUT'){const b=await r.json();await e.DB.prepare('UPDATE tenant_tags SET name=?,parent_id=? WHERE tenant_id=? AND id=?').bind(clean(b.name,100),clean(b.parent_id,100)||null,id,tid).run();return J({ok:true})}}
  if(p==='/api/tenant/comments'&&r.method==='GET')return J({ok:true,comments:(await e.DB.prepare('SELECT id,name,text,image,created_at FROM tenant_comments WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100').bind(id).all()).results||[]});
  let tc=p.match(/^\/api\/tenant\/comments\/([^/]+)$/);if(tc&&r.method==='DELETE'){await e.DB.prepare('DELETE FROM tenant_comments WHERE tenant_id=? AND id=?').bind(id,tc[1]).run();return J({ok:true})}
  if(p==='/api/tenant/settings'&&r.method==='GET')return J({ok:true,settings:await tenantSettings(e,id)});
  if(p==='/api/tenant/settings'&&r.method==='PUT'){const b=await r.json();const allowed=['siteName','studio','heroTitle','heroText','avatar','announcementTitle','announcementText','announcementEnabled','groupLink','adminContact','adminZalo','donateTitle','donateText','donateQr'];for(const [k,v] of Object.entries(b)){if(!allowed.includes(k))continue;await e.DB.prepare('INSERT INTO tenant_settings(tenant_id,key,value) VALUES(?,?,?) ON CONFLICT(tenant_id,key) DO UPDATE SET value=excluded.value').bind(id,k,JSON.stringify(v)).run()}await tenantAudit(e,id,'update_settings','Cập nhật giao diện');return J({ok:true})}
  if(p==='/api/tenant/stats'&&r.method==='GET')return J({ok:true,...await tenantStats(e,id,new URL(r.url).searchParams.get('days')||30)});
  if(p==='/api/tenant/audit'&&r.method==='GET')return J({ok:true,logs:(await e.DB.prepare('SELECT * FROM tenant_audit_log WHERE tenant_id=? ORDER BY id DESC LIMIT 100').bind(id).all()).results||[]});
  return J({ok:false,error:'NOT_FOUND'},404)
}
async function handleMasterTenant(r,e,p){
  if(!(await isAdmin(r,e)))return J({ok:false,error:'ADMIN_REQUIRED'},401);
  if(p==='/api/admin/tenants'&&r.method==='GET'){const q=clean(new URL(r.url).searchParams.get('q')||'',100);const rows=(await e.DB.prepare(`SELECT tenant_id,password_hash,slug,starts_at,expires_at,delete_after,locked,created_at,updated_at FROM tenant_accounts WHERE tenant_id LIKE ? ORDER BY created_at DESC`).bind('%'+q+'%').all()).results||[];return J({ok:true,tenants:rows.map(x=>tenantInfo(x))})}
  if(p==='/api/admin/tenants'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const tid=clean(b.tenant_id,80),pw=String(b.password||''),days=Math.max(1,Math.min(Number(b.days)||30,3650));if(!/^[A-Za-z0-9_-]{3,80}$/.test(tid))return J({ok:false,error:'INVALID_ID'},400);if(pw.length<6)return J({ok:false,error:'PASSWORD_TOO_SHORT'},400);if(await e.DB.prepare('SELECT tenant_id FROM tenant_accounts WHERE tenant_id=?').bind(tid).first())return J({ok:false,error:'ID_EXISTS'},409);const st=now(),ex=st+days*86400000,slug=makeSlug(tid);await e.DB.prepare('INSERT INTO tenant_accounts(tenant_id,password_hash,slug,starts_at,expires_at,delete_after,locked) VALUES(?,?,?,?,?,?,0)').bind(tid,await sha256(pw),slug,st,ex,ex+6*86400000).run();await tenantAudit(e,tid,'created','Tạo tài khoản thuê');const defaults={siteName:'Lại Húp File',studio:'Téo Studio',heroTitle:'Téo Studio',heroText:'Kho code, script, tool và tài nguyên game được cập nhật.',avatar:'assets/img/default-avatar.svg',announcementEnabled:true,adminContact:'#',adminZalo:'#',groupLink:'#'};for(const [k,v] of Object.entries(defaults))await e.DB.prepare('INSERT OR IGNORE INTO tenant_settings(tenant_id,key,value) VALUES(?,?,?)').bind(tid,k,JSON.stringify(v)).run();return J({ok:true,tenant:{id:tid,slug,startsAt:st,expiresAt:ex,daysLeft:days,status:'active'},adminUrl:`/tenant-admin.html?tenant=${encodeURIComponent(slug)}`,shareUrl:`/share.html?tenant=${encodeURIComponent(slug)}`},201)}
  let tm=p.match(/^\/api\/admin\/tenants\/([^/]+)$/);if(tm){const tid=decodeURIComponent(tm[1]);const a=await e.DB.prepare('SELECT * FROM tenant_accounts WHERE tenant_id=?').bind(tid).first();if(!a)return J({ok:false,error:'TENANT_NOT_FOUND'},404);if(r.method==='DELETE'){await e.DB.batch([e.DB.prepare('DELETE FROM tenant_sessions WHERE tenant_id=?').bind(tid),e.DB.prepare('DELETE FROM tenant_products WHERE tenant_id=?').bind(tid),e.DB.prepare('DELETE FROM tenant_tags WHERE tenant_id=?').bind(tid),e.DB.prepare('DELETE FROM tenant_comments WHERE tenant_id=?').bind(tid),e.DB.prepare('DELETE FROM tenant_settings WHERE tenant_id=?').bind(tid),e.DB.prepare('DELETE FROM tenant_views WHERE tenant_id=?').bind(tid),e.DB.prepare('DELETE FROM tenant_audit_log WHERE tenant_id=?').bind(tid),e.DB.prepare('DELETE FROM tenant_accounts WHERE tenant_id=?').bind(tid)]);return J({ok:true})}}
  let tr=p.match(/^\/api\/admin\/tenants\/([^/]+)\/(renew|password|lock|unlock|reset-sessions|audit)$/);if(tr){const tid=decodeURIComponent(tr[1]),action=tr[2],a=await e.DB.prepare('SELECT * FROM tenant_accounts WHERE tenant_id=?').bind(tid).first();if(!a)return J({ok:false,error:'TENANT_NOT_FOUND'},404);if(action==='renew'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const d=Math.max(1,Math.min(Number(b.days)||30,3650));const base=Math.max(now(),Number(a.expires_at));const ex=base+d*86400000;await e.DB.prepare('UPDATE tenant_accounts SET expires_at=?,delete_after=?,locked=0,updated_at=datetime(\'now\') WHERE tenant_id=?').bind(ex,ex+6*86400000,tid).run();await tenantAudit(e,tid,'renew',`+${d} ngày`);return J({ok:true,tenant:tenantInfo({...a,expires_at:ex,delete_after:ex+6*86400000,locked:0})})}if(action==='password'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const pw=String(b.password||'');if(pw.length<6)return J({ok:false,error:'PASSWORD_TOO_SHORT'},400);await e.DB.prepare('UPDATE tenant_accounts SET password_hash=?,updated_at=datetime(\'now\') WHERE tenant_id=?').bind(await sha256(pw),tid).run();await e.DB.prepare('DELETE FROM tenant_sessions WHERE tenant_id=?').bind(tid).run();await tenantAudit(e,tid,'admin_reset_password','Master đổi mật khẩu tenant');return J({ok:true})}if(action==='lock'&&r.method==='POST'){await e.DB.prepare('UPDATE tenant_accounts SET locked=1,updated_at=datetime(\'now\') WHERE tenant_id=?').bind(tid).run();await e.DB.prepare('DELETE FROM tenant_sessions WHERE tenant_id=?').bind(tid).run();return J({ok:true})}if(action==='unlock'&&r.method==='POST'){await e.DB.prepare('UPDATE tenant_accounts SET locked=0,updated_at=datetime(\'now\') WHERE tenant_id=?').bind(tid).run();return J({ok:true})}if(action==='reset-sessions'&&r.method==='POST'){await e.DB.prepare('DELETE FROM tenant_sessions WHERE tenant_id=?').bind(tid).run();return J({ok:true})}if(action==='audit'&&r.method==='GET')return J({ok:true,logs:(await e.DB.prepare('SELECT * FROM tenant_audit_log WHERE tenant_id=? ORDER BY id DESC LIMIT 100').bind(tid).all()).results||[]})}
  return J({ok:false,error:'NOT_FOUND'},404)
}
export default{
 async fetch(r,e){
  if(r.method==='OPTIONS')return new Response(null,{headers:C});
  const u=new URL(r.url),p=u.pathname.replace(/\/$/,'');
  try{
   await ensureSchema(e);
   if(p==='/api/health')return J({ok:true,service:'teo-studio-api',version:'rental-1',d1:true});
   if(p==='/api/tenant/login'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const id=clean(b.tenant_id,80),pw=String(b.password||'');const a=await e.DB.prepare('SELECT * FROM tenant_accounts WHERE tenant_id=?').bind(id).first();if(!a)return J({ok:false,error:'INVALID_LOGIN'},401);if(Number(a.locked))return J({ok:false,error:'TENANT_LOCKED'},403);if(Number(a.expires_at)<=now())return J({ok:false,error:'TENANT_EXPIRED',deleteAfter:a.delete_after},403);if((await sha256(pw))!==a.password_hash)return J({ok:false,error:'INVALID_LOGIN'},401);const token=crypto.randomUUID()+crypto.randomUUID();await e.DB.prepare('INSERT INTO tenant_sessions(token,tenant_id,expires_at) VALUES(?,?,?)').bind(token,id,now()+7*86400000).run();await tenantAudit(e,id,'login','Tenant đăng nhập');return J({ok:true,token,tenant:tenantInfo(a),shareUrl:`/share.html?tenant=${encodeURIComponent(a.slug)}`,adminUrl:`/tenant-admin.html?tenant=${encodeURIComponent(a.slug)}`})}
   if(p.startsWith('/api/tenant/')&&p!=='/api/tenant/login')return await handleTenantAdmin(r,e,p);
   if(p.startsWith('/api/admin/tenants'))return await handleMasterTenant(r,e,p);
   if(p.startsWith('/api/public-tenant/'))return await handleTenantPublic(r,e,p.replace('/api/public-tenant','/tenant'));
   await purgeExpired(e);
   if(p==='/api/products'&&r.method==='GET')return J({ok:true,products:await products(e)});
   if(p.match(/^\/api\/products\/[^/]+$/)&&r.method==='GET'){const id=decodeURIComponent(p.split('/').pop());const product=await productById(e,id);return product?J({ok:true,product}):J({ok:false,error:'NOT_FOUND'},404)}
   if(p==='/api/tags'&&r.method==='GET')return J({ok:true,tags:await tags(e)});
   if(p==='/api/settings'&&r.method==='GET')return J({ok:true,settings:await settings(e)});
   if(p==='/api/comments'&&r.method==='GET')return J({ok:true,comments:await comments(e)});
   if(p==='/api/comments'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const name=clean(b.name,40)||'Ẩn danh',text=clean(b.text,700),image=clean(b.image,1000000);if(!text&&!image)return J({ok:false,error:'COMMENT_EMPTY'},400);const id=crypto.randomUUID();await e.DB.prepare('INSERT INTO comments(id,name,text,image) VALUES(?,?,?,?)').bind(id,name,text,image).run();return J({ok:true,id},201)}
   if(p==='/api/track/site'&&r.method==='POST'){await bumpView(e,'site');return J({ok:true})}
   let tv=p.match(/^\/api\/track\/product\/([^/]+)$/);if(tv&&r.method==='POST'){const id=decodeURIComponent(tv[1]);const product=await productById(e,id);if(!product)return J({ok:false,error:'NOT_FOUND'},404);await bumpView(e,'product',id);return J({ok:true,views:Number(product.views||0)+1})}
   let to=p.match(/^\/api\/track\/outbound\/([^/]+)$/);if(to&&r.method==='POST'){const id=decodeURIComponent(to[1]);const product=await productById(e,id);if(!product)return J({ok:false,error:'NOT_FOUND'},404);await bumpView(e,'outbound',id);return J({ok:true})}
   if(p==='/api/admin/login'&&r.method==='POST'){const b=await r.json().catch(()=>({}));const row=await e.DB.prepare('SELECT password_hash FROM admin_auth WHERE id=1').first();const ok=row&&(await sha256(clean(b.password,200)))===row.password_hash;if(!ok)return J({ok:false,error:'INVALID_PASSWORD'},401);const token=crypto.randomUUID()+crypto.randomUUID();await e.DB.prepare('INSERT INTO admin_sessions(token,expires_at) VALUES(?,?)').bind(token,now()+7*86400000).run();return J({ok:true,token,expiresIn:7*86400000})}
   if(p==='/api/admin/logout'&&r.method==='POST'){const t=tokenFrom(r);if(t)await e.DB.prepare('DELETE FROM admin_sessions WHERE token=?').bind(t).run();return J({ok:true})}
   if(p==='/api/admin/change-password'&&r.method==='POST'){if(!(await isAdmin(r,e)))return J({ok:false,error:'ADMIN_REQUIRED'},401);const b=await r.json().catch(()=>({}));if(!b.newPassword||String(b.newPassword).length<6)return J({ok:false,error:'PASSWORD_TOO_SHORT'},400);await e.DB.prepare('UPDATE admin_auth SET password_hash=?,updated_at=datetime(\'now\') WHERE id=1').bind(await sha256(String(b.newPassword))).run();return J({ok:true})}
   if(!(await isAdmin(r,e)))return J({ok:false,error:'ADMIN_REQUIRED'},401);
   if(p==='/api/admin/stats'&&r.method==='GET')return J({ok:true,...await stats(e,new URL(r.url).searchParams.get('days')||30)});
   if(p==='/api/admin/comments'&&r.method==='GET')return J({ok:true,comments:await comments(e)});
   let cm=p.match(/^\/api\/admin\/comments\/([^/]+)$/);if(cm&&r.method==='DELETE'){await e.DB.prepare('DELETE FROM comments WHERE id=?').bind(cm[1]).run();return J({ok:true})}
   if(p==='/api/admin/products'&&r.method==='GET')return J({ok:true,products:await adminProducts(e)});
   if(p==='/api/admin/products'&&r.method==='POST'){const b=await r.json();if(!b.title||!b.download_link)return J({ok:false,error:'title_and_download_link_required'},400);const id=crypto.randomUUID();await e.DB.prepare('INSERT INTO products(id,title,game,description,thumb,download_link,warning,visible) VALUES(?,?,?,?,?,?,?,1)').bind(id,clean(b.title,200),clean(b.game,100),clean(b.description),clean(b.thumb,1500000),clean(b.download_link,10000),clean(b.warning)).run();return J({ok:true,id},201)}
   let m=p.match(/^\/api\/admin\/products\/([^/]+)$/);if(m){const id=m[1];if(r.method==='DELETE'){await e.DB.prepare('DELETE FROM products WHERE id=?').bind(id).run();return J({ok:true})}if(r.method==='PUT'){const b=await r.json();await e.DB.prepare('UPDATE products SET title=?,game=?,description=?,thumb=?,download_link=?,warning=?,updated_at=datetime(\'now\') WHERE id=?').bind(clean(b.title,200),clean(b.game,100),clean(b.description),clean(b.thumb,1500000),clean(b.download_link,10000),clean(b.warning),id).run();return J({ok:true})}}
   if(p==='/api/admin/tags'&&r.method==='POST'){const b=await r.json(),name=clean(b.name,100),parentId=clean(b.parent_id,100);if(!name)return J({ok:false,error:'name_required'},400);const id=crypto.randomUUID();await e.DB.prepare('INSERT INTO tags(id,name,parent_id) VALUES(?,?,?)').bind(id,name,parentId||null).run();return J({ok:true,id},201)}
   let t=p.match(/^\/api\/admin\/tags\/([^/]+)$/);if(t){const id=t[1];if(r.method==='DELETE'){await e.DB.prepare('DELETE FROM tags WHERE id=? OR parent_id=?').bind(id,id).run();return J({ok:true})}if(r.method==='PUT'){const b=await r.json();await e.DB.prepare('UPDATE tags SET name=?,parent_id=? WHERE id=?').bind(clean(b.name,100),clean(b.parent_id,100)||null,id).run();return J({ok:true})}}
   if(p==='/api/admin/settings'&&r.method==='GET')return J({ok:true,settings:await settings(e)});
   if(p==='/api/admin/settings'&&r.method==='PUT'){const b=await r.json();for(const [k,v] of Object.entries(b)){if(!['siteName','studio','heroTitle','heroText','avatar','announcementTitle','announcementText','announcementEnabled','groupLink','adminContact','adminZalo','donateTitle','donateText','donateQr','avatarVideoUrl'].includes(k))continue;await e.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,JSON.stringify(v)).run()}return J({ok:true})}
   if(e.ASSETS)return e.ASSETS.fetch(r);return J({ok:false,error:'NOT_FOUND'},404)
  }catch(x){return J({ok:false,error:'SERVER_ERROR',detail:String(x.message||x)},500)}
 },
 async scheduled(controller,e){try{await ensureSchema(e);await purgeExpired(e)}catch(err){console.log('tenant cleanup failed',String(err))}}
};
